FROM mongo
RUN apt update
RUN apt install python3 python3-pip -y
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
ADD backend/requirements.txt /
RUN pip3 install --no-cache-dir -r requirements.txt
ADD backend/main.py ./
RUN pip3 install flask
ENV FLASK_APP=backend/main.py
RUN pip3 list
CMD ["flask", "--app", "main", "run", "--host", "0.0.0.0"]